#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="uses")]
	public partial class demoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbantin(bantin instance);
    partial void Updatebantin(bantin instance);
    partial void Deletebantin(bantin instance);
    partial void Insertchitiet(chitiet instance);
    partial void Updatechitiet(chitiet instance);
    partial void Deletechitiet(chitiet instance);
    partial void Insertname(name instance);
    partial void Updatename(name instance);
    partial void Deletename(name instance);
    partial void Insertsanpham(sanpham instance);
    partial void Updatesanpham(sanpham instance);
    partial void Deletesanpham(sanpham instance);
    partial void Insertdanhmuc(danhmuc instance);
    partial void Updatedanhmuc(danhmuc instance);
    partial void Deletedanhmuc(danhmuc instance);
    #endregion
		
		public demoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["usesConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public demoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public demoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public demoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public demoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<bantin> bantins
		{
			get
			{
				return this.GetTable<bantin>();
			}
		}
		
		public System.Data.Linq.Table<chitiet> chitiets
		{
			get
			{
				return this.GetTable<chitiet>();
			}
		}
		
		public System.Data.Linq.Table<name> names
		{
			get
			{
				return this.GetTable<name>();
			}
		}
		
		public System.Data.Linq.Table<sanpham> sanphams
		{
			get
			{
				return this.GetTable<sanpham>();
			}
		}
		
		public System.Data.Linq.Table<danhmuc> danhmucs
		{
			get
			{
				return this.GetTable<danhmuc>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.bantin_selectall")]
		public ISingleResult<bantin_selectallResult> bantin_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<bantin_selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.bantin_selectid")]
		public ISingleResult<bantin_selectidResult> bantin_selectid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idbantin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idbantin);
			return ((ISingleResult<bantin_selectidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checkad")]
		public ISingleResult<checkadResult> checkad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email);
			return ((ISingleResult<checkadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.danhmuc_selectall")]
		public ISingleResult<danhmuc_selectallResult> danhmuc_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<danhmuc_selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.danhmuc_selectid")]
		public ISingleResult<danhmuc_selectidResult> danhmuc_selectid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<danhmuc_selectidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.menu_selectall")]
		public ISingleResult<menu_selectallResult> menu_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<menu_selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.name_checkad")]
		public ISingleResult<name_checkadResult> name_checkad([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email);
			return ((ISingleResult<name_checkadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.name_download")]
		public ISingleResult<name_downloadResult> name_download([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> download)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, download);
			return ((ISingleResult<name_downloadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.name_insertinto")]
		public int name_insertinto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string passwors)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, passwors);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.name_search")]
		public ISingleResult<name_searchResult> name_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, password);
			return ((ISingleResult<name_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.name_selectall")]
		public ISingleResult<name_selectallResult> name_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<name_selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.name_selectname")]
		public ISingleResult<name_selectnameResult> name_selectname([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((ISingleResult<name_selectnameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sabpham_luottai")]
		public int sabpham_luottai([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idsanpham, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> luottai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idsanpham, luottai);
			luottai = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sanpham_download")]
		public int sanpham_download([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> download)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, download);
			download = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sanpham_home")]
		public ISingleResult<sanpham_homeResult> sanpham_home()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sanpham_homeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sanpham_insert")]
		public int sanpham_insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string sanpham, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string noidung, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> download, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> iddanhmuc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string linktai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sanpham, noidung, download, iddanhmuc, linktai);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sanpham_selectall")]
		public ISingleResult<sanpham_selectallResult> sanpham_selectall()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sanpham_selectallResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sanpham_selectid")]
		public ISingleResult<sanpham_selectidResult> sanpham_selectid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idsanpham)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idsanpham);
			return ((ISingleResult<sanpham_selectidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sanpham_selectiddanhmuc")]
		public ISingleResult<sanpham_selectiddanhmucResult> sanpham_selectiddanhmuc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> iddanhmuc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iddanhmuc);
			return ((ISingleResult<sanpham_selectiddanhmucResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sanpham_updatelt")]
		public int sanpham_updatelt([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idsanpham, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> luottai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idsanpham, luottai);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sanpham_xephang")]
		public ISingleResult<sanpham_xephangResult> sanpham_xephang()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sanpham_xephangResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.chitiet_insertinto")]
		public int chitiet_insertinto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idbantin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string tieude, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string gioithieu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string noidung, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaydang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string linkart)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idbantin, tieude, gioithieu, noidung, ngaydang, linkart);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.chitiet_home")]
		public ISingleResult<chitiet_homeResult> chitiet_home()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<chitiet_homeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.chitiet_selectid")]
		public ISingleResult<chitiet_selectidResult> chitiet_selectid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idchitiet)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idchitiet);
			return ((ISingleResult<chitiet_selectidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.chitiet_selectidbantin")]
		public ISingleResult<chitiet_selectidbantinResult> chitiet_selectidbantin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idbantin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idbantin);
			return ((ISingleResult<chitiet_selectidbantinResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.chitiet_selectnew")]
		public ISingleResult<chitiet_selectnewResult> chitiet_selectnew()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<chitiet_selectnewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.chitiet_selectrandom")]
		public ISingleResult<chitiet_selectrandomResult> chitiet_selectrandom([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idbantin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idbantin);
			return ((ISingleResult<chitiet_selectrandomResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sanpham_searchbyname")]
		public ISingleResult<sanpham_searchbynameResult> sanpham_searchbyname([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string sanpham)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sanpham);
			return ((ISingleResult<sanpham_searchbynameResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bantin")]
	public partial class bantin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idbantin;
		
		private string _bantin1;
		
		private EntitySet<chitiet> _chitiets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidbantinChanging(int value);
    partial void OnidbantinChanged();
    partial void Onbantin1Changing(string value);
    partial void Onbantin1Changed();
    #endregion
		
		public bantin()
		{
			this._chitiets = new EntitySet<chitiet>(new Action<chitiet>(this.attach_chitiets), new Action<chitiet>(this.detach_chitiets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idbantin", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idbantin
		{
			get
			{
				return this._idbantin;
			}
			set
			{
				if ((this._idbantin != value))
				{
					this.OnidbantinChanging(value);
					this.SendPropertyChanging();
					this._idbantin = value;
					this.SendPropertyChanged("idbantin");
					this.OnidbantinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="bantin", Storage="_bantin1", DbType="NVarChar(50)")]
		public string bantin1
		{
			get
			{
				return this._bantin1;
			}
			set
			{
				if ((this._bantin1 != value))
				{
					this.Onbantin1Changing(value);
					this.SendPropertyChanging();
					this._bantin1 = value;
					this.SendPropertyChanged("bantin1");
					this.Onbantin1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bantin_chitiet", Storage="_chitiets", ThisKey="idbantin", OtherKey="idbantin")]
		public EntitySet<chitiet> chitiets
		{
			get
			{
				return this._chitiets;
			}
			set
			{
				this._chitiets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitiets(chitiet entity)
		{
			this.SendPropertyChanging();
			entity.bantin = this;
		}
		
		private void detach_chitiets(chitiet entity)
		{
			this.SendPropertyChanging();
			entity.bantin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitiet")]
	public partial class chitiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idchitiet;
		
		private string _tieude;
		
		private string _gioithieu;
		
		private string _noidung;
		
		private System.Nullable<System.DateTime> _ngaydang;
		
		private System.Nullable<int> _idbantin;
		
		private string _linkart;
		
		private EntityRef<bantin> _bantin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidchitietChanging(int value);
    partial void OnidchitietChanged();
    partial void OntieudeChanging(string value);
    partial void OntieudeChanged();
    partial void OngioithieuChanging(string value);
    partial void OngioithieuChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnngaydangChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydangChanged();
    partial void OnidbantinChanging(System.Nullable<int> value);
    partial void OnidbantinChanged();
    partial void OnlinkartChanging(string value);
    partial void OnlinkartChanged();
    #endregion
		
		public chitiet()
		{
			this._bantin = default(EntityRef<bantin>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idchitiet", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idchitiet
		{
			get
			{
				return this._idchitiet;
			}
			set
			{
				if ((this._idchitiet != value))
				{
					this.OnidchitietChanging(value);
					this.SendPropertyChanging();
					this._idchitiet = value;
					this.SendPropertyChanged("idchitiet");
					this.OnidchitietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this.OntieudeChanging(value);
					this.SendPropertyChanging();
					this._tieude = value;
					this.SendPropertyChanged("tieude");
					this.OntieudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioithieu", DbType="NVarChar(500)")]
		public string gioithieu
		{
			get
			{
				return this._gioithieu;
			}
			set
			{
				if ((this._gioithieu != value))
				{
					this.OngioithieuChanging(value);
					this.SendPropertyChanging();
					this._gioithieu = value;
					this.SendPropertyChanged("gioithieu");
					this.OngioithieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydang
		{
			get
			{
				return this._ngaydang;
			}
			set
			{
				if ((this._ngaydang != value))
				{
					this.OnngaydangChanging(value);
					this.SendPropertyChanging();
					this._ngaydang = value;
					this.SendPropertyChanged("ngaydang");
					this.OnngaydangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idbantin", DbType="Int")]
		public System.Nullable<int> idbantin
		{
			get
			{
				return this._idbantin;
			}
			set
			{
				if ((this._idbantin != value))
				{
					if (this._bantin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidbantinChanging(value);
					this.SendPropertyChanging();
					this._idbantin = value;
					this.SendPropertyChanged("idbantin");
					this.OnidbantinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkart", DbType="NVarChar(MAX)")]
		public string linkart
		{
			get
			{
				return this._linkart;
			}
			set
			{
				if ((this._linkart != value))
				{
					this.OnlinkartChanging(value);
					this.SendPropertyChanging();
					this._linkart = value;
					this.SendPropertyChanged("linkart");
					this.OnlinkartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bantin_chitiet", Storage="_bantin", ThisKey="idbantin", OtherKey="idbantin", IsForeignKey=true)]
		public bantin bantin
		{
			get
			{
				return this._bantin.Entity;
			}
			set
			{
				bantin previousValue = this._bantin.Entity;
				if (((previousValue != value) 
							|| (this._bantin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bantin.Entity = null;
						previousValue.chitiets.Remove(this);
					}
					this._bantin.Entity = value;
					if ((value != null))
					{
						value.chitiets.Add(this);
						this._idbantin = value.idbantin;
					}
					else
					{
						this._idbantin = default(Nullable<int>);
					}
					this.SendPropertyChanged("bantin");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.name")]
	public partial class name : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _email;
		
		private string _password;
		
		private System.Nullable<int> _downloaded;
		
		private System.Nullable<int> _adm;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OndownloadedChanging(System.Nullable<int> value);
    partial void OndownloadedChanged();
    partial void OnadmChanging(System.Nullable<int> value);
    partial void OnadmChanged();
    #endregion
		
		public name()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="Char(10)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downloaded", DbType="Int")]
		public System.Nullable<int> downloaded
		{
			get
			{
				return this._downloaded;
			}
			set
			{
				if ((this._downloaded != value))
				{
					this.OndownloadedChanging(value);
					this.SendPropertyChanging();
					this._downloaded = value;
					this.SendPropertyChanged("downloaded");
					this.OndownloadedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adm", DbType="Int")]
		public System.Nullable<int> adm
		{
			get
			{
				return this._adm;
			}
			set
			{
				if ((this._adm != value))
				{
					this.OnadmChanging(value);
					this.SendPropertyChanging();
					this._adm = value;
					this.SendPropertyChanged("adm");
					this.OnadmChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sanpham")]
	public partial class sanpham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idsanpham;
		
		private string _sanpham1;
		
		private string _noidung;
		
		private string _rate;
		
		private System.Nullable<int> _luottai;
		
		private System.Nullable<int> _download;
		
		private System.Nullable<int> _iddanhmuc;
		
		private string _linktai;
		
		private EntityRef<danhmuc> _danhmuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidsanphamChanging(int value);
    partial void OnidsanphamChanged();
    partial void Onsanpham1Changing(string value);
    partial void Onsanpham1Changed();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnrateChanging(string value);
    partial void OnrateChanged();
    partial void OnluottaiChanging(System.Nullable<int> value);
    partial void OnluottaiChanged();
    partial void OndownloadChanging(System.Nullable<int> value);
    partial void OndownloadChanged();
    partial void OniddanhmucChanging(System.Nullable<int> value);
    partial void OniddanhmucChanged();
    partial void OnlinktaiChanging(string value);
    partial void OnlinktaiChanged();
    #endregion
		
		public sanpham()
		{
			this._danhmuc = default(EntityRef<danhmuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idsanpham", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idsanpham
		{
			get
			{
				return this._idsanpham;
			}
			set
			{
				if ((this._idsanpham != value))
				{
					this.OnidsanphamChanging(value);
					this.SendPropertyChanging();
					this._idsanpham = value;
					this.SendPropertyChanged("idsanpham");
					this.OnidsanphamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sanpham", Storage="_sanpham1", DbType="NVarChar(100)")]
		public string sanpham1
		{
			get
			{
				return this._sanpham1;
			}
			set
			{
				if ((this._sanpham1 != value))
				{
					this.Onsanpham1Changing(value);
					this.SendPropertyChanging();
					this._sanpham1 = value;
					this.SendPropertyChanged("sanpham1");
					this.Onsanpham1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate", DbType="NChar(10)")]
		public string rate
		{
			get
			{
				return this._rate;
			}
			set
			{
				if ((this._rate != value))
				{
					this.OnrateChanging(value);
					this.SendPropertyChanging();
					this._rate = value;
					this.SendPropertyChanged("rate");
					this.OnrateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luottai", DbType="Int")]
		public System.Nullable<int> luottai
		{
			get
			{
				return this._luottai;
			}
			set
			{
				if ((this._luottai != value))
				{
					this.OnluottaiChanging(value);
					this.SendPropertyChanging();
					this._luottai = value;
					this.SendPropertyChanged("luottai");
					this.OnluottaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_download", DbType="Int")]
		public System.Nullable<int> download
		{
			get
			{
				return this._download;
			}
			set
			{
				if ((this._download != value))
				{
					this.OndownloadChanging(value);
					this.SendPropertyChanging();
					this._download = value;
					this.SendPropertyChanged("download");
					this.OndownloadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddanhmuc", DbType="Int")]
		public System.Nullable<int> iddanhmuc
		{
			get
			{
				return this._iddanhmuc;
			}
			set
			{
				if ((this._iddanhmuc != value))
				{
					if (this._danhmuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OniddanhmucChanging(value);
					this.SendPropertyChanging();
					this._iddanhmuc = value;
					this.SendPropertyChanged("iddanhmuc");
					this.OniddanhmucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linktai", DbType="NVarChar(MAX)")]
		public string linktai
		{
			get
			{
				return this._linktai;
			}
			set
			{
				if ((this._linktai != value))
				{
					this.OnlinktaiChanging(value);
					this.SendPropertyChanging();
					this._linktai = value;
					this.SendPropertyChanged("linktai");
					this.OnlinktaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="danhmuc_sanpham", Storage="_danhmuc", ThisKey="iddanhmuc", OtherKey="iddanhmuc", IsForeignKey=true)]
		public danhmuc danhmuc
		{
			get
			{
				return this._danhmuc.Entity;
			}
			set
			{
				danhmuc previousValue = this._danhmuc.Entity;
				if (((previousValue != value) 
							|| (this._danhmuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._danhmuc.Entity = null;
						previousValue.sanphams.Remove(this);
					}
					this._danhmuc.Entity = value;
					if ((value != null))
					{
						value.sanphams.Add(this);
						this._iddanhmuc = value.iddanhmuc;
					}
					else
					{
						this._iddanhmuc = default(Nullable<int>);
					}
					this.SendPropertyChanged("danhmuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.danhmuc")]
	public partial class danhmuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iddanhmuc;
		
		private string _danhmuc1;
		
		private EntitySet<sanpham> _sanphams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniddanhmucChanging(int value);
    partial void OniddanhmucChanged();
    partial void Ondanhmuc1Changing(string value);
    partial void Ondanhmuc1Changed();
    #endregion
		
		public danhmuc()
		{
			this._sanphams = new EntitySet<sanpham>(new Action<sanpham>(this.attach_sanphams), new Action<sanpham>(this.detach_sanphams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddanhmuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iddanhmuc
		{
			get
			{
				return this._iddanhmuc;
			}
			set
			{
				if ((this._iddanhmuc != value))
				{
					this.OniddanhmucChanging(value);
					this.SendPropertyChanging();
					this._iddanhmuc = value;
					this.SendPropertyChanged("iddanhmuc");
					this.OniddanhmucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="danhmuc", Storage="_danhmuc1", DbType="NVarChar(50)")]
		public string danhmuc1
		{
			get
			{
				return this._danhmuc1;
			}
			set
			{
				if ((this._danhmuc1 != value))
				{
					this.Ondanhmuc1Changing(value);
					this.SendPropertyChanging();
					this._danhmuc1 = value;
					this.SendPropertyChanged("danhmuc1");
					this.Ondanhmuc1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="danhmuc_sanpham", Storage="_sanphams", ThisKey="iddanhmuc", OtherKey="iddanhmuc")]
		public EntitySet<sanpham> sanphams
		{
			get
			{
				return this._sanphams;
			}
			set
			{
				this._sanphams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.danhmuc = this;
		}
		
		private void detach_sanphams(sanpham entity)
		{
			this.SendPropertyChanging();
			entity.danhmuc = null;
		}
	}
	
	public partial class bantin_selectallResult
	{
		
		private int _idbantin;
		
		private string _bantin;
		
		public bantin_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idbantin", DbType="Int NOT NULL")]
		public int idbantin
		{
			get
			{
				return this._idbantin;
			}
			set
			{
				if ((this._idbantin != value))
				{
					this._idbantin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bantin", DbType="NVarChar(50)")]
		public string bantin
		{
			get
			{
				return this._bantin;
			}
			set
			{
				if ((this._bantin != value))
				{
					this._bantin = value;
				}
			}
		}
	}
	
	public partial class bantin_selectidResult
	{
		
		private int _idbantin;
		
		private string _bantin;
		
		public bantin_selectidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idbantin", DbType="Int NOT NULL")]
		public int idbantin
		{
			get
			{
				return this._idbantin;
			}
			set
			{
				if ((this._idbantin != value))
				{
					this._idbantin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bantin", DbType="NVarChar(50)")]
		public string bantin
		{
			get
			{
				return this._bantin;
			}
			set
			{
				if ((this._bantin != value))
				{
					this._bantin = value;
				}
			}
		}
	}
	
	public partial class checkadResult
	{
		
		private string _email;
		
		private string _password;
		
		private System.Nullable<int> _downloaded;
		
		private System.Nullable<int> _adm;
		
		public checkadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="Char(10)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downloaded", DbType="Int")]
		public System.Nullable<int> downloaded
		{
			get
			{
				return this._downloaded;
			}
			set
			{
				if ((this._downloaded != value))
				{
					this._downloaded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adm", DbType="Int")]
		public System.Nullable<int> adm
		{
			get
			{
				return this._adm;
			}
			set
			{
				if ((this._adm != value))
				{
					this._adm = value;
				}
			}
		}
	}
	
	public partial class danhmuc_selectallResult
	{
		
		private int _iddanhmuc;
		
		private string _danhmuc;
		
		public danhmuc_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddanhmuc", DbType="Int NOT NULL")]
		public int iddanhmuc
		{
			get
			{
				return this._iddanhmuc;
			}
			set
			{
				if ((this._iddanhmuc != value))
				{
					this._iddanhmuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danhmuc", DbType="NVarChar(50)")]
		public string danhmuc
		{
			get
			{
				return this._danhmuc;
			}
			set
			{
				if ((this._danhmuc != value))
				{
					this._danhmuc = value;
				}
			}
		}
	}
	
	public partial class danhmuc_selectidResult
	{
		
		private int _iddanhmuc;
		
		private string _danhmuc;
		
		public danhmuc_selectidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddanhmuc", DbType="Int NOT NULL")]
		public int iddanhmuc
		{
			get
			{
				return this._iddanhmuc;
			}
			set
			{
				if ((this._iddanhmuc != value))
				{
					this._iddanhmuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danhmuc", DbType="NVarChar(50)")]
		public string danhmuc
		{
			get
			{
				return this._danhmuc;
			}
			set
			{
				if ((this._danhmuc != value))
				{
					this._danhmuc = value;
				}
			}
		}
	}
	
	public partial class menu_selectallResult
	{
		
		private int _idmenu;
		
		private string _tenviet;
		
		private string _teneng;
		
		private string _link;
		
		public menu_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idmenu", DbType="Int NOT NULL")]
		public int idmenu
		{
			get
			{
				return this._idmenu;
			}
			set
			{
				if ((this._idmenu != value))
				{
					this._idmenu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenviet", DbType="NVarChar(50)")]
		public string tenviet
		{
			get
			{
				return this._tenviet;
			}
			set
			{
				if ((this._tenviet != value))
				{
					this._tenviet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teneng", DbType="NChar(10)")]
		public string teneng
		{
			get
			{
				return this._teneng;
			}
			set
			{
				if ((this._teneng != value))
				{
					this._teneng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NChar(50)")]
		public string link
		{
			get
			{
				return this._link;
			}
			set
			{
				if ((this._link != value))
				{
					this._link = value;
				}
			}
		}
	}
	
	public partial class name_checkadResult
	{
		
		private string _email;
		
		private string _password;
		
		private System.Nullable<int> _downloaded;
		
		private System.Nullable<int> _adm;
		
		public name_checkadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="Char(10)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downloaded", DbType="Int")]
		public System.Nullable<int> downloaded
		{
			get
			{
				return this._downloaded;
			}
			set
			{
				if ((this._downloaded != value))
				{
					this._downloaded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adm", DbType="Int")]
		public System.Nullable<int> adm
		{
			get
			{
				return this._adm;
			}
			set
			{
				if ((this._adm != value))
				{
					this._adm = value;
				}
			}
		}
	}
	
	public partial class name_downloadResult
	{
		
		private string _email;
		
		private string _password;
		
		private System.Nullable<int> _downloaded;
		
		private System.Nullable<int> _adm;
		
		public name_downloadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="Char(10)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downloaded", DbType="Int")]
		public System.Nullable<int> downloaded
		{
			get
			{
				return this._downloaded;
			}
			set
			{
				if ((this._downloaded != value))
				{
					this._downloaded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adm", DbType="Int")]
		public System.Nullable<int> adm
		{
			get
			{
				return this._adm;
			}
			set
			{
				if ((this._adm != value))
				{
					this._adm = value;
				}
			}
		}
	}
	
	public partial class name_searchResult
	{
		
		private string _email;
		
		private string _password;
		
		private System.Nullable<int> _downloaded;
		
		private System.Nullable<int> _adm;
		
		public name_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="Char(10)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downloaded", DbType="Int")]
		public System.Nullable<int> downloaded
		{
			get
			{
				return this._downloaded;
			}
			set
			{
				if ((this._downloaded != value))
				{
					this._downloaded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adm", DbType="Int")]
		public System.Nullable<int> adm
		{
			get
			{
				return this._adm;
			}
			set
			{
				if ((this._adm != value))
				{
					this._adm = value;
				}
			}
		}
	}
	
	public partial class name_selectallResult
	{
		
		private string _email;
		
		private string _password;
		
		private System.Nullable<int> _downloaded;
		
		private System.Nullable<int> _adm;
		
		public name_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="Char(10)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downloaded", DbType="Int")]
		public System.Nullable<int> downloaded
		{
			get
			{
				return this._downloaded;
			}
			set
			{
				if ((this._downloaded != value))
				{
					this._downloaded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adm", DbType="Int")]
		public System.Nullable<int> adm
		{
			get
			{
				return this._adm;
			}
			set
			{
				if ((this._adm != value))
				{
					this._adm = value;
				}
			}
		}
	}
	
	public partial class name_selectnameResult
	{
		
		private string _email;
		
		private string _password;
		
		private System.Nullable<int> _downloaded;
		
		private System.Nullable<int> _adm;
		
		public name_selectnameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="Char(10)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_downloaded", DbType="Int")]
		public System.Nullable<int> downloaded
		{
			get
			{
				return this._downloaded;
			}
			set
			{
				if ((this._downloaded != value))
				{
					this._downloaded = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adm", DbType="Int")]
		public System.Nullable<int> adm
		{
			get
			{
				return this._adm;
			}
			set
			{
				if ((this._adm != value))
				{
					this._adm = value;
				}
			}
		}
	}
	
	public partial class sanpham_homeResult
	{
		
		private int _idsanpham;
		
		private string _sanpham;
		
		private string _noidung;
		
		private string _rate;
		
		private System.Nullable<int> _luottai;
		
		private System.Nullable<int> _download;
		
		private System.Nullable<int> _iddanhmuc;
		
		private string _linktai;
		
		public sanpham_homeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idsanpham", DbType="Int NOT NULL")]
		public int idsanpham
		{
			get
			{
				return this._idsanpham;
			}
			set
			{
				if ((this._idsanpham != value))
				{
					this._idsanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham", DbType="NVarChar(100)")]
		public string sanpham
		{
			get
			{
				return this._sanpham;
			}
			set
			{
				if ((this._sanpham != value))
				{
					this._sanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate", DbType="NChar(10)")]
		public string rate
		{
			get
			{
				return this._rate;
			}
			set
			{
				if ((this._rate != value))
				{
					this._rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luottai", DbType="Int")]
		public System.Nullable<int> luottai
		{
			get
			{
				return this._luottai;
			}
			set
			{
				if ((this._luottai != value))
				{
					this._luottai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_download", DbType="Int")]
		public System.Nullable<int> download
		{
			get
			{
				return this._download;
			}
			set
			{
				if ((this._download != value))
				{
					this._download = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddanhmuc", DbType="Int")]
		public System.Nullable<int> iddanhmuc
		{
			get
			{
				return this._iddanhmuc;
			}
			set
			{
				if ((this._iddanhmuc != value))
				{
					this._iddanhmuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linktai", DbType="NVarChar(MAX)")]
		public string linktai
		{
			get
			{
				return this._linktai;
			}
			set
			{
				if ((this._linktai != value))
				{
					this._linktai = value;
				}
			}
		}
	}
	
	public partial class sanpham_selectallResult
	{
		
		private int _idsanpham;
		
		private string _sanpham;
		
		private string _noidung;
		
		private string _rate;
		
		private System.Nullable<int> _luottai;
		
		private System.Nullable<int> _download;
		
		private System.Nullable<int> _iddanhmuc;
		
		private string _linktai;
		
		public sanpham_selectallResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idsanpham", DbType="Int NOT NULL")]
		public int idsanpham
		{
			get
			{
				return this._idsanpham;
			}
			set
			{
				if ((this._idsanpham != value))
				{
					this._idsanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham", DbType="NVarChar(100)")]
		public string sanpham
		{
			get
			{
				return this._sanpham;
			}
			set
			{
				if ((this._sanpham != value))
				{
					this._sanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate", DbType="NChar(10)")]
		public string rate
		{
			get
			{
				return this._rate;
			}
			set
			{
				if ((this._rate != value))
				{
					this._rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luottai", DbType="Int")]
		public System.Nullable<int> luottai
		{
			get
			{
				return this._luottai;
			}
			set
			{
				if ((this._luottai != value))
				{
					this._luottai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_download", DbType="Int")]
		public System.Nullable<int> download
		{
			get
			{
				return this._download;
			}
			set
			{
				if ((this._download != value))
				{
					this._download = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddanhmuc", DbType="Int")]
		public System.Nullable<int> iddanhmuc
		{
			get
			{
				return this._iddanhmuc;
			}
			set
			{
				if ((this._iddanhmuc != value))
				{
					this._iddanhmuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linktai", DbType="NVarChar(MAX)")]
		public string linktai
		{
			get
			{
				return this._linktai;
			}
			set
			{
				if ((this._linktai != value))
				{
					this._linktai = value;
				}
			}
		}
	}
	
	public partial class sanpham_selectidResult
	{
		
		private int _idsanpham;
		
		private string _sanpham;
		
		private string _noidung;
		
		private string _rate;
		
		private System.Nullable<int> _luottai;
		
		private System.Nullable<int> _download;
		
		private System.Nullable<int> _iddanhmuc;
		
		private string _linktai;
		
		public sanpham_selectidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idsanpham", DbType="Int NOT NULL")]
		public int idsanpham
		{
			get
			{
				return this._idsanpham;
			}
			set
			{
				if ((this._idsanpham != value))
				{
					this._idsanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham", DbType="NVarChar(100)")]
		public string sanpham
		{
			get
			{
				return this._sanpham;
			}
			set
			{
				if ((this._sanpham != value))
				{
					this._sanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate", DbType="NChar(10)")]
		public string rate
		{
			get
			{
				return this._rate;
			}
			set
			{
				if ((this._rate != value))
				{
					this._rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luottai", DbType="Int")]
		public System.Nullable<int> luottai
		{
			get
			{
				return this._luottai;
			}
			set
			{
				if ((this._luottai != value))
				{
					this._luottai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_download", DbType="Int")]
		public System.Nullable<int> download
		{
			get
			{
				return this._download;
			}
			set
			{
				if ((this._download != value))
				{
					this._download = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddanhmuc", DbType="Int")]
		public System.Nullable<int> iddanhmuc
		{
			get
			{
				return this._iddanhmuc;
			}
			set
			{
				if ((this._iddanhmuc != value))
				{
					this._iddanhmuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linktai", DbType="NVarChar(MAX)")]
		public string linktai
		{
			get
			{
				return this._linktai;
			}
			set
			{
				if ((this._linktai != value))
				{
					this._linktai = value;
				}
			}
		}
	}
	
	public partial class sanpham_selectiddanhmucResult
	{
		
		private int _idsanpham;
		
		private string _sanpham;
		
		private string _noidung;
		
		private string _rate;
		
		private System.Nullable<int> _luottai;
		
		private System.Nullable<int> _download;
		
		private System.Nullable<int> _iddanhmuc;
		
		private string _linktai;
		
		public sanpham_selectiddanhmucResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idsanpham", DbType="Int NOT NULL")]
		public int idsanpham
		{
			get
			{
				return this._idsanpham;
			}
			set
			{
				if ((this._idsanpham != value))
				{
					this._idsanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham", DbType="NVarChar(100)")]
		public string sanpham
		{
			get
			{
				return this._sanpham;
			}
			set
			{
				if ((this._sanpham != value))
				{
					this._sanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate", DbType="NChar(10)")]
		public string rate
		{
			get
			{
				return this._rate;
			}
			set
			{
				if ((this._rate != value))
				{
					this._rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luottai", DbType="Int")]
		public System.Nullable<int> luottai
		{
			get
			{
				return this._luottai;
			}
			set
			{
				if ((this._luottai != value))
				{
					this._luottai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_download", DbType="Int")]
		public System.Nullable<int> download
		{
			get
			{
				return this._download;
			}
			set
			{
				if ((this._download != value))
				{
					this._download = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddanhmuc", DbType="Int")]
		public System.Nullable<int> iddanhmuc
		{
			get
			{
				return this._iddanhmuc;
			}
			set
			{
				if ((this._iddanhmuc != value))
				{
					this._iddanhmuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linktai", DbType="NVarChar(MAX)")]
		public string linktai
		{
			get
			{
				return this._linktai;
			}
			set
			{
				if ((this._linktai != value))
				{
					this._linktai = value;
				}
			}
		}
	}
	
	public partial class sanpham_xephangResult
	{
		
		private int _idsanpham;
		
		private string _sanpham;
		
		private string _noidung;
		
		private string _rate;
		
		private System.Nullable<int> _luottai;
		
		private System.Nullable<int> _download;
		
		private System.Nullable<int> _iddanhmuc;
		
		private string _linktai;
		
		public sanpham_xephangResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idsanpham", DbType="Int NOT NULL")]
		public int idsanpham
		{
			get
			{
				return this._idsanpham;
			}
			set
			{
				if ((this._idsanpham != value))
				{
					this._idsanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham", DbType="NVarChar(100)")]
		public string sanpham
		{
			get
			{
				return this._sanpham;
			}
			set
			{
				if ((this._sanpham != value))
				{
					this._sanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate", DbType="NChar(10)")]
		public string rate
		{
			get
			{
				return this._rate;
			}
			set
			{
				if ((this._rate != value))
				{
					this._rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luottai", DbType="Int")]
		public System.Nullable<int> luottai
		{
			get
			{
				return this._luottai;
			}
			set
			{
				if ((this._luottai != value))
				{
					this._luottai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_download", DbType="Int")]
		public System.Nullable<int> download
		{
			get
			{
				return this._download;
			}
			set
			{
				if ((this._download != value))
				{
					this._download = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddanhmuc", DbType="Int")]
		public System.Nullable<int> iddanhmuc
		{
			get
			{
				return this._iddanhmuc;
			}
			set
			{
				if ((this._iddanhmuc != value))
				{
					this._iddanhmuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linktai", DbType="NVarChar(MAX)")]
		public string linktai
		{
			get
			{
				return this._linktai;
			}
			set
			{
				if ((this._linktai != value))
				{
					this._linktai = value;
				}
			}
		}
	}
	
	public partial class chitiet_homeResult
	{
		
		private int _idchitiet;
		
		private string _tieude;
		
		private string _gioithieu;
		
		private string _noidung;
		
		private System.Nullable<System.DateTime> _ngaydang;
		
		private System.Nullable<int> _idbantin;
		
		private string _linkart;
		
		public chitiet_homeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idchitiet", DbType="Int NOT NULL")]
		public int idchitiet
		{
			get
			{
				return this._idchitiet;
			}
			set
			{
				if ((this._idchitiet != value))
				{
					this._idchitiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioithieu", DbType="NVarChar(500)")]
		public string gioithieu
		{
			get
			{
				return this._gioithieu;
			}
			set
			{
				if ((this._gioithieu != value))
				{
					this._gioithieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydang
		{
			get
			{
				return this._ngaydang;
			}
			set
			{
				if ((this._ngaydang != value))
				{
					this._ngaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idbantin", DbType="Int")]
		public System.Nullable<int> idbantin
		{
			get
			{
				return this._idbantin;
			}
			set
			{
				if ((this._idbantin != value))
				{
					this._idbantin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkart", DbType="NVarChar(MAX)")]
		public string linkart
		{
			get
			{
				return this._linkart;
			}
			set
			{
				if ((this._linkart != value))
				{
					this._linkart = value;
				}
			}
		}
	}
	
	public partial class chitiet_selectidResult
	{
		
		private int _idchitiet;
		
		private string _tieude;
		
		private string _gioithieu;
		
		private string _noidung;
		
		private System.Nullable<System.DateTime> _ngaydang;
		
		private System.Nullable<int> _idbantin;
		
		private string _linkart;
		
		public chitiet_selectidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idchitiet", DbType="Int NOT NULL")]
		public int idchitiet
		{
			get
			{
				return this._idchitiet;
			}
			set
			{
				if ((this._idchitiet != value))
				{
					this._idchitiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioithieu", DbType="NVarChar(500)")]
		public string gioithieu
		{
			get
			{
				return this._gioithieu;
			}
			set
			{
				if ((this._gioithieu != value))
				{
					this._gioithieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydang
		{
			get
			{
				return this._ngaydang;
			}
			set
			{
				if ((this._ngaydang != value))
				{
					this._ngaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idbantin", DbType="Int")]
		public System.Nullable<int> idbantin
		{
			get
			{
				return this._idbantin;
			}
			set
			{
				if ((this._idbantin != value))
				{
					this._idbantin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkart", DbType="NVarChar(MAX)")]
		public string linkart
		{
			get
			{
				return this._linkart;
			}
			set
			{
				if ((this._linkart != value))
				{
					this._linkart = value;
				}
			}
		}
	}
	
	public partial class chitiet_selectidbantinResult
	{
		
		private int _idchitiet;
		
		private string _tieude;
		
		private string _gioithieu;
		
		private string _noidung;
		
		private System.Nullable<System.DateTime> _ngaydang;
		
		private System.Nullable<int> _idbantin;
		
		private string _linkart;
		
		public chitiet_selectidbantinResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idchitiet", DbType="Int NOT NULL")]
		public int idchitiet
		{
			get
			{
				return this._idchitiet;
			}
			set
			{
				if ((this._idchitiet != value))
				{
					this._idchitiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioithieu", DbType="NVarChar(500)")]
		public string gioithieu
		{
			get
			{
				return this._gioithieu;
			}
			set
			{
				if ((this._gioithieu != value))
				{
					this._gioithieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydang
		{
			get
			{
				return this._ngaydang;
			}
			set
			{
				if ((this._ngaydang != value))
				{
					this._ngaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idbantin", DbType="Int")]
		public System.Nullable<int> idbantin
		{
			get
			{
				return this._idbantin;
			}
			set
			{
				if ((this._idbantin != value))
				{
					this._idbantin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkart", DbType="NVarChar(MAX)")]
		public string linkart
		{
			get
			{
				return this._linkart;
			}
			set
			{
				if ((this._linkart != value))
				{
					this._linkart = value;
				}
			}
		}
	}
	
	public partial class chitiet_selectnewResult
	{
		
		private int _idchitiet;
		
		private string _tieude;
		
		private string _gioithieu;
		
		private string _noidung;
		
		private System.Nullable<System.DateTime> _ngaydang;
		
		private System.Nullable<int> _idbantin;
		
		private string _linkart;
		
		public chitiet_selectnewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idchitiet", DbType="Int NOT NULL")]
		public int idchitiet
		{
			get
			{
				return this._idchitiet;
			}
			set
			{
				if ((this._idchitiet != value))
				{
					this._idchitiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioithieu", DbType="NVarChar(500)")]
		public string gioithieu
		{
			get
			{
				return this._gioithieu;
			}
			set
			{
				if ((this._gioithieu != value))
				{
					this._gioithieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydang
		{
			get
			{
				return this._ngaydang;
			}
			set
			{
				if ((this._ngaydang != value))
				{
					this._ngaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idbantin", DbType="Int")]
		public System.Nullable<int> idbantin
		{
			get
			{
				return this._idbantin;
			}
			set
			{
				if ((this._idbantin != value))
				{
					this._idbantin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkart", DbType="NVarChar(MAX)")]
		public string linkart
		{
			get
			{
				return this._linkart;
			}
			set
			{
				if ((this._linkart != value))
				{
					this._linkart = value;
				}
			}
		}
	}
	
	public partial class chitiet_selectrandomResult
	{
		
		private int _idchitiet;
		
		private string _tieude;
		
		private string _gioithieu;
		
		private string _noidung;
		
		private System.Nullable<System.DateTime> _ngaydang;
		
		private System.Nullable<int> _idbantin;
		
		private string _linkart;
		
		public chitiet_selectrandomResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idchitiet", DbType="Int NOT NULL")]
		public int idchitiet
		{
			get
			{
				return this._idchitiet;
			}
			set
			{
				if ((this._idchitiet != value))
				{
					this._idchitiet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioithieu", DbType="NVarChar(500)")]
		public string gioithieu
		{
			get
			{
				return this._gioithieu;
			}
			set
			{
				if ((this._gioithieu != value))
				{
					this._gioithieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydang", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydang
		{
			get
			{
				return this._ngaydang;
			}
			set
			{
				if ((this._ngaydang != value))
				{
					this._ngaydang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idbantin", DbType="Int")]
		public System.Nullable<int> idbantin
		{
			get
			{
				return this._idbantin;
			}
			set
			{
				if ((this._idbantin != value))
				{
					this._idbantin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkart", DbType="NVarChar(MAX)")]
		public string linkart
		{
			get
			{
				return this._linkart;
			}
			set
			{
				if ((this._linkart != value))
				{
					this._linkart = value;
				}
			}
		}
	}
	
	public partial class sanpham_searchbynameResult
	{
		
		private int _idsanpham;
		
		private string _sanpham;
		
		private string _noidung;
		
		private string _rate;
		
		private System.Nullable<int> _luottai;
		
		private System.Nullable<int> _download;
		
		private System.Nullable<int> _iddanhmuc;
		
		private string _linktai;
		
		public sanpham_searchbynameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idsanpham", DbType="Int NOT NULL")]
		public int idsanpham
		{
			get
			{
				return this._idsanpham;
			}
			set
			{
				if ((this._idsanpham != value))
				{
					this._idsanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sanpham", DbType="NVarChar(100)")]
		public string sanpham
		{
			get
			{
				return this._sanpham;
			}
			set
			{
				if ((this._sanpham != value))
				{
					this._sanpham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rate", DbType="NChar(10)")]
		public string rate
		{
			get
			{
				return this._rate;
			}
			set
			{
				if ((this._rate != value))
				{
					this._rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luottai", DbType="Int")]
		public System.Nullable<int> luottai
		{
			get
			{
				return this._luottai;
			}
			set
			{
				if ((this._luottai != value))
				{
					this._luottai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_download", DbType="Int")]
		public System.Nullable<int> download
		{
			get
			{
				return this._download;
			}
			set
			{
				if ((this._download != value))
				{
					this._download = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iddanhmuc", DbType="Int")]
		public System.Nullable<int> iddanhmuc
		{
			get
			{
				return this._iddanhmuc;
			}
			set
			{
				if ((this._iddanhmuc != value))
				{
					this._iddanhmuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linktai", DbType="NVarChar(MAX)")]
		public string linktai
		{
			get
			{
				return this._linktai;
			}
			set
			{
				if ((this._linktai != value))
				{
					this._linktai = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
